/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities */
        get: operations["list_opportunities_api_v1_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity */
        get: operations["get_opportunity_api_v1_opportunities__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OpportunityDetail */
        OpportunityDetail: {
            /**
             * Ai Source Match
             * @default false
             */
            ai_source_match: boolean;
            /**
             * Category
             * @enum {string}
             */
            category: "scholarship" | "internship" | "competition";
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Deadline */
            deadline: string | null;
            /** Description */
            description: string;
            /** Eligibility */
            eligibility: string;
            /** Issuer Name */
            issuer_name: string;
            /** Region */
            region: string | null;
            /** Slug */
            slug: string;
            /** Source Url */
            source_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "expired" | "needs_review";
            /** Title */
            title: string;
            /**
             * Trust Basis
             * @enum {string}
             */
            trust_basis: "public_source" | "issuer_confirmed_private";
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
        };
        /** OpportunityListResponse */
        OpportunityListResponse: {
            /** Items */
            items: components["schemas"]["OpportunitySummary"][];
            /** Total */
            total: number;
        };
        /** OpportunitySummary */
        OpportunitySummary: {
            /**
             * Ai Source Match
             * @default false
             */
            ai_source_match: boolean;
            /**
             * Category
             * @enum {string}
             */
            category: "scholarship" | "internship" | "competition";
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Deadline */
            deadline: string | null;
            /** Issuer Name */
            issuer_name: string;
            /** Slug */
            slug: string;
            /** Source Url */
            source_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "expired" | "needs_review";
            /** Title */
            title: string;
            /**
             * Trust Basis
             * @enum {string}
             */
            trust_basis: "public_source" | "issuer_confirmed_private";
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_opportunities_api_v1_opportunities_get: {
        parameters: {
            query?: {
                category?: ("scholarship" | "internship" | "competition") | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_api_v1_opportunities__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
