/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities */
        get: operations["list_opportunities_api_v1_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/incoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Incoming Feed
         * @description Public feed of AI-checked submissions awaiting moderator review.
         *
         *     Every row is an unmoderated submission — 'ai_checked' must never be
         *     presented as a trust badge; it upgrades to 'moderator_verified' only
         *     when a human approves it into the catalogue.
         */
        get: operations["list_incoming_feed_api_v1_opportunities_incoming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/incoming/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incoming Item */
        get: operations["get_incoming_item_api_v1_opportunities_incoming__ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity */
        get: operations["get_opportunity_api_v1_opportunities__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{slug}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Opportunity
         * @description Public community report; flags the listing for moderator review only.
         *
         *     Rate-limited per client network hash. Creating a report never touches the
         *     opportunity's status or trust fields.
         */
        post: operations["report_opportunity_api_v1_opportunities__slug__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Submission */
        post: operations["create_submission_api_v1_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Duplicate
         * @description Pre-submit duplicate lookup on the normalized URL.
         */
        get: operations["check_duplicate_api_v1_submissions_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission Status */
        get: operations["get_submission_status_api_v1_submissions__ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submissions */
        get: operations["list_submissions_api_v1_moderation_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission Detail */
        get: operations["get_submission_detail_api_v1_moderation_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/submissions/{submission_id}/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Upload
         * @description Stream a stored upload for moderator review.
         *
         *     The upload row is looked up by id and must belong to the submission;
         *     upload_file_path resolves storage_key under UPLOAD_DIR and refuses any
         *     path outside it, so no user input ever reaches the filesystem.
         */
        get: operations["download_upload_api_v1_moderation_submissions__submission_id__uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/submissions/{submission_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Decision */
        post: operations["post_decision_api_v1_moderation_submissions__submission_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Login */
        post: operations["auth_cookie_login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth:Cookie.Logout */
        post: operations["auth_cookie_logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users:Current User */
        get: operations["users_current_user_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_auth_cookie_login_api_v1_auth_login_post */
        Body_auth_cookie_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_create_submission_api_v1_submissions_post */
        Body_create_submission_api_v1_submissions_post: {
            /** Url */
            url?: string | null;
            /** Context */
            context?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /**
         * DecisionFields
         * @description Opportunity payload a moderator supplies when approving a submission.
         */
        DecisionFields: {
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "scholarship" | "internship" | "competition";
            /** Description */
            description: string;
            /** Eligibility */
            eligibility: string;
            /** Region */
            region?: string | null;
            /** Deadline */
            deadline?: string | null;
            /** Slug */
            slug?: string | null;
            /** Issuer Name */
            issuer_name?: string | null;
            /**
             * Trust Basis
             * @default public_source
             * @enum {string}
             */
            trust_basis: "public_source" | "issuer_confirmed_private";
        };
        /** DecisionRequest */
        DecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "needs_more_evidence" | "rejected" | "expire";
            /** Reason */
            reason?: string | null;
            fields?: components["schemas"]["DecisionFields"] | null;
        };
        /** DecisionResult */
        DecisionResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /** Submission State */
            submission_state: string;
            /** Opportunity Slug */
            opportunity_slug?: string | null;
        };
        /** DecisionView */
        DecisionView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Reason */
            reason: string | null;
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
        };
        /**
         * DedupeCheck
         * @description Pre-submit duplicate check. 'listing' points at a catalogue entry,
         *     'incoming' at a pending submission whose screening can be shown
         *     immediately.
         */
        DedupeCheck: {
            /** Duplicate */
            duplicate: boolean;
            /** Kind */
            kind?: ("listing" | "incoming") | null;
            /** Slug */
            slug?: string | null;
            /** Title */
            title?: string | null;
            /** Status */
            status?: string | null;
            /** Ref */
            ref?: string | null;
            screening?: components["schemas"]["ScreeningView"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IncomingItem
         * @description Public feed row: an AI-checked submission awaiting moderation.
         */
        IncomingItem: {
            /** Ref */
            ref: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Verification
             * @constant
             */
            verification: "ai_checked";
            /** Submitted Url */
            submitted_url: string | null;
            screening: components["schemas"]["ScreeningView"] | null;
        };
        /** IncomingListResponse */
        IncomingListResponse: {
            /** Items */
            items: components["schemas"]["IncomingItem"][];
            /** Total */
            total: number;
        };
        /** OpportunityDetail */
        OpportunityDetail: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "scholarship" | "internship" | "competition";
            /** Issuer Name */
            issuer_name: string;
            /** Deadline */
            deadline: string | null;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
            /**
             * Trust Basis
             * @enum {string}
             */
            trust_basis: "public_source" | "issuer_confirmed_private";
            /**
             * Verification
             * @default moderator_verified
             * @enum {string}
             */
            verification: "ai_checked" | "moderator_verified";
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "expired" | "needs_review";
            /** Source Url */
            source_url: string | null;
            /** Ai Source Match */
            ai_source_match?: boolean | null;
            /** Description */
            description: string;
            /** Eligibility */
            eligibility: string;
            /** Region */
            region: string | null;
        };
        /** OpportunityListResponse */
        OpportunityListResponse: {
            /** Items */
            items: components["schemas"]["OpportunitySummary"][];
            /** Total */
            total: number;
        };
        /** OpportunitySummary */
        OpportunitySummary: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "scholarship" | "internship" | "competition";
            /** Issuer Name */
            issuer_name: string;
            /** Deadline */
            deadline: string | null;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
            /**
             * Trust Basis
             * @enum {string}
             */
            trust_basis: "public_source" | "issuer_confirmed_private";
            /**
             * Verification
             * @default moderator_verified
             * @enum {string}
             */
            verification: "ai_checked" | "moderator_verified";
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "expired" | "needs_review";
            /** Source Url */
            source_url: string | null;
            /** Ai Source Match */
            ai_source_match?: boolean | null;
        };
        /** QueueItem */
        QueueItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ref */
            ref: string;
            /** State */
            state: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Submitted Url Host */
            submitted_url_host: string | null;
            /** Uploads Count */
            uploads_count: number;
            /** Has Contact Email */
            has_contact_email: boolean;
            /** Open Reports Count */
            open_reports_count: number;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Items */
            items: components["schemas"]["QueueItem"][];
            /** Total */
            total: number;
        };
        /** ReportCreated */
        ReportCreated: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ReportRequest */
        ReportRequest: {
            /**
             * Category
             * @enum {string}
             */
            category: "scam_suspect" | "deadline_wrong" | "link_broken" | "info_incorrect" | "other";
            /** Description */
            description?: string | null;
        };
        /** ReportView */
        ReportView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Category */
            category: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ScreeningErrorView */
        ScreeningErrorView: {
            /** Stage */
            stage: string | null;
            /** Kind */
            kind: string | null;
        };
        /** ScreeningRunMeta */
        ScreeningRunMeta: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** State */
            state: string;
            /** Provider Version */
            provider_version: string | null;
            /** Model Version */
            model_version: string | null;
            /** Schema Version */
            schema_version: string | null;
            /** Result Json */
            result_json: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ScreeningView
         * @description Guest/public-safe projection of a screening run — extracted fields,
         *     per-field source verdicts, and the official-source signal. No
         *     submission_text, evidence bodies, or provider internals.
         */
        ScreeningView: {
            /** State */
            state: string;
            /** Outcome */
            outcome: string | null;
            /** Extracted */
            extracted: {
                [key: string]: unknown;
            } | null;
            /** Field Verdicts */
            field_verdicts: {
                [key: string]: unknown;
            } | null;
            /** Sources */
            sources: components["schemas"]["SourceCheck"][];
            /** Ai Source Match */
            ai_source_match: boolean | null;
            /** Errors */
            errors: components["schemas"]["ScreeningErrorView"][];
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * SourceCheck
         * @description One fetched source page and whether Jev judged it the issuer's
         *     official listing. Body text is never exposed publicly.
         */
        SourceCheck: {
            /** Url */
            url: string;
            /** Status */
            status: number | null;
            /** Official */
            official: boolean | null;
            /** Error */
            error?: string | null;
        };
        /** SubmissionCreated */
        SubmissionCreated: {
            /** Ref */
            ref: string;
            /** Receipt Token */
            receipt_token: string;
            /** Status */
            status: string;
            /** Status Url */
            status_url: string;
        };
        /**
         * SubmissionDetail
         * @description Everything a moderator sees; receipt_token_hash is never included.
         */
        SubmissionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ref */
            ref: string;
            /** State */
            state: string;
            /** Submitted Url */
            submitted_url: string | null;
            /** Context */
            context: string;
            /** Contact Email */
            contact_email: string | null;
            /** Client Net Hash */
            client_net_hash: string;
            /** Purge After */
            purge_after: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Uploads */
            uploads: components["schemas"]["UploadMeta"][];
            screening_run: components["schemas"]["ScreeningRunMeta"] | null;
            /** Decisions */
            decisions: components["schemas"]["DecisionView"][];
            /** Linked Opportunity Slug */
            linked_opportunity_slug: string | null;
            /** Reports */
            reports: components["schemas"]["ReportView"][];
        };
        /** SubmissionStatus */
        SubmissionStatus: {
            /** Ref */
            ref: string;
            /** State */
            state: string;
            /** Status Label */
            status_label: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision */
            decision?: string | null;
            /**
             * Needs More Evidence
             * @default false
             */
            needs_more_evidence: boolean;
            screening?: components["schemas"]["ScreeningView"] | null;
        };
        /** UploadMeta */
        UploadMeta: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Storage Key */
            storage_key: string;
            /** Detected Mime */
            detected_mime: string;
            /** Size Bytes */
            size_bytes: number;
            /** Page Count */
            page_count: number | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_opportunities_api_v1_opportunities_get: {
        parameters: {
            query?: {
                category?: ("scholarship" | "internship" | "competition") | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incoming_feed_api_v1_opportunities_incoming_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incoming_item_api_v1_opportunities_incoming__ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_api_v1_opportunities__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_opportunity_api_v1_opportunities__slug__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_api_v1_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_submission_api_v1_submissions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_duplicate_api_v1_submissions_check_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupeCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_status_api_v1_submissions__ref__get: {
        parameters: {
            query?: never;
            header: {
                "x-receipt-token": string;
            };
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submissions_api_v1_moderation_submissions_get: {
        parameters: {
            query?: {
                state?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_detail_api_v1_moderation_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_upload_api_v1_moderation_submissions__submission_id__uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_decision_api_v1_moderation_submissions__submission_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_cookie_login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_auth_cookie_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_cookie_logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_current_user_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
}
