"""create trusted catalogue

Revision ID: f751c5dcc7ff
Revises: 
Create Date: 2026-09-26 19:33:02.225728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f751c5dcc7ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issuers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issuer_domains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('source_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_evidence_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('issuer_id', sa.Uuid(), nullable=False),
    sa.Column('issuer_domain_id', sa.Uuid(), nullable=False),
    sa.Column('source_evidence_id', sa.Uuid(), nullable=False),
    sa.Column('moderation_decision_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('eligibility', sa.String(), nullable=False),
    sa.Column('region', sa.String(length=160), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('trust_basis', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['issuer_domain_id'], ['issuer_domains.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ),
    sa.ForeignKeyConstraint(['moderation_decision_id'], ['moderation_decisions.id'], ),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_events')
    op.drop_table('opportunities')
    op.drop_table('moderation_decisions')
    op.drop_table('source_evidence')
    op.drop_table('issuer_domains')
    op.drop_table('issuers')
    # ### end Alembic commands ###
